### ISSUE TITLE
Implement (proper) support for configuring multi-datapaths

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#112]
At the moment we only support configuring multiple datapath elements via running separate instances of Faucet with different configuration files (on separate ports)

This makes it annoying to manage multiple OpenFlow-enabled switches since we need to assign separate TCP ports for each to connect back to our multiple Faucet instances.

In original Valve we had the ability to list multiple DPIDs in the configuration file that would be configured (with different numbers of ports and different vlan assignments).

I think this change will require a change to the config file format since there doesn't appear to be an easy way to list additional datapaths in there.

**Comment by KitL** [comment]
The config file format should not need to be changed. Multiple datapaths can be read as multiple documents within the single file (IE separate them with a "---" line). It will require changing how the configs are read though, the files are currently being read by the DP object, which doesnt make sense if it is reading in multiple DP objects from a single file..

**Comment by shivarammysore** [comment]
Can you also make sure that documentation is updated accordingly as this impacts how Faucet is used?  Thanks

**Comment by gizmoguy** [comment]
Also will need appropriate example config files added to the repo and tests written.

We're thinking this will make a good SDNcon project for someone if no one else gets to it first.

**Comment by gwacter** [comment]
That's a good idea, I'll add it to the list.

**Comment by Callum027** [comment]
Hi all,

So the Victoria team at SDNcon took on this project, and we implemented it, changing the configuration format along the way. Our changes are being tracked [here](https://github.com/gwacter/faucet/tree/multiple-dps), in @gwacter's local branch.

Configuring multiple DPs currently looks something like this:

```yaml
dps:
    1:
        dp_id: 0x000000000001
        name: "test-switch-1"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1
    2:
        dp_id: 0x000000000002
        name: "test-switch-2"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1

vlans:
    2040:
        name: "dev VLAN"

acls:
    1:
        - rule:
            nw_dst: "172.0.0.0/8"
            dl_type: 0x800
            allow: 1

        - rule:
            dl_type: 0x0806
            allow: 1

        - rule:
            nw_dst: "10.0.0.0/16"
            dl_type: 0x800
            allow: 0

        - rule:
```

I understand this will need some discussion before it gets merged because it breaks the current configuration format (although we could probably add backwards compatibility), so @gizmoguy and I had a quick chat and thought it would be a good idea for me to post here and start a discussion to determine what format this change should ultimately take, and when it should be merged (when version 2.0 is branched off for development?)

In the mean time, we'll clean up our code, add documentation, write associated tests and make a pull request when it is ready.

**Comment by anarkiwi** [comment]
Hi Callum and Brad;

This sure is nice! Thanks for doing this - I imagine you have looked into
inter DP connections as well? I can imagine building larger switches out of
individual DPs will come in handy.

Can we enumerate the DPs directly by DP ID? Seems to be no need for a
separate index?

**Comment by gizmoguy** [comment]
Hi guys.

I agree with @anarkiwi that we should probably just enumerate by DP_ID (like we did back in Valve) so it would look a bit like this:

```
dps:
    0x000000000001:
        name: "test-switch-1"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1
    0x000000000002:
        name: "test-switch-2"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1
```

@KitL also had an idea of using separate YAML documents for each DP_ID which might make backwards compatibility a bit nicer, however it makes sharing VLANs between DP_IDs difficult which is what I like about the approach @Callum027 etc have taken.

**Comment by anarkiwi** [comment]
While not backward compatible, I think this is a big enough step forward to
go through the inconvenience of changing it (especially while the number of
deployments is relatively low).

I have been thinking also of adding "include file" support, which would
allow splitting out relatively static parts of the config from more dynamic
parts, which would then allow automation to change parts of the config
perhaps with different permissions. However that probably deserves a thread
of its own.

Can I suggest that as part of the merge process, that the new config file
format be implemented as a PR by itself? It should accept only one DPID.

**Comment by vladimir-mencl-eresearch** [comment]
Hi guys,

Listening in, I have a suggestion regarding the config file format change.

When Docker was changing the format of the docker-compose.yml file, they introduced the config file syntax version into the syntax.

So when using the new syntax, you start your config file with:

    version: '2'

This makes it easy for the parser to know which version to parse - and makes it possible to support both versions of the syntax.  And for future changes, it gives you each config file tagged with the version of the syntax it was written it...

More info + examples at https://docs.docker.com/compose/compose-file/#/versioning

Hope this helps!

Cheers,
Vlad

**Comment by Callum027** [comment]
@gizmoguy, we can change the indexes to use the DPID directly, no problem. We initially used the numerical indexing because we thought it would make it more consistent with other data structures with the configuration format, but having it as you and @anarkiwi suggested would be better, as the numerical index serves no other real purpose.

@anarkiwi, so you would like there to be two PRs, one with the new config file format specifying the `dps` data structure along with other changes, and another one implementing multiple DP support within Faucet itself? We can do that if that's what you prefer.

@vladimir-mencl-eresearch, that is up to the REANNZ folks but I think this is a good idea. We could have `version` default to `1` if it is not specified, until the next major release, where the default should be fine to change to `2`.

**Comment by anarkiwi** [comment]
Yes please - a PR that changes the config file format and only supports one
DPID (iike today).

That should make the merge/review/test process considerably easier.

Yes please also on config file version - great idea.

Thanks,

On Tue, Jul 12, 2016 at 10:16 AM, Callum Dickinson <notifications@github.com

**Comment by Callum027** [comment]
I've made a fourth branch, [gwacter/new-config-format](https://github.com/gwacter/faucet/tree/new-config-format), to track the new configuration format. I've implemented it as discussed, so if `version` is not specified or is set to `1`, it will parse the configuration as before, and if it is set to `2`, it will use a different version of the `parse` method which parses for `dps` (but of course, will only actually use the first one).

The configuration format would look like this:
```yaml
version: 2

dps:
    0x000000000001:
        name: "test-switch-1"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1
    0x000000000002:
        name: "test-switch-2"
        interfaces:
            1:
                native_vlan: 2040
                acl_in: 1

vlans:
    2040:
        name: "dev VLAN"

acls:
    1:
        - rule:
            nw_dst: "172.0.0.0/8"
            dl_type: 0x800
            allow: 1

        - rule:
            dl_type: 0x0806
            allow: 1

        - rule:
            nw_dst: "10.0.0.0/16"
            dl_type: 0x800
            allow: 0

        - rule:
```
I will test that the changes work (I am at home at the moment so no testbed to play with), and then make a PR.

For the documentation, should we modify the Configuration section of `README.rst` to elaborate a bit more on the configuration format, or would you rather there be two sample configuration files, one for each version?
