### ISSUE TITLE
Consistency of configuration structure

### ISSUE THREAD

**Issue by KitL** [REANNZ/faucet#126]
I am touching up my change that does most of this. I just wanted to check a couple of things through with you guys before I change too much more.

Firstly this is kind of a big change. Here is an overview:

The main goal is to have consistency between how faucet and gauge are configured. I migrate gauge to using yaml, and make the database configuration actually configurable. I also try to make gauge and faucet more consistent in how the code is structured.

The  gauge config looks something like this:
```

valve_configs:
        - "faucet1.yaml"
        - "/etc/ryu/faucet/faucet2.yaml"
pollers:
        flow_table_poller:     #the name of the poller
                gauge_type: "flow_table"
                dps: ["switch-1", "switch-2", "switch-3"]
                interval: 60
                db: "flow_table_file"
        port_state_poller:
                gauge_type:"port_state"
                dps: ["office-switch-1"]
                db: "influx"
dbs:
        influx:
               type: "influx"
                db: "faucet"
                host: "localhost"
                port: 8086
        flow_table_file:
                type: "text"
               output_file: "gauge_flow_table.txt"
```

For consistencies sake I would like to change it so all of the configuration for faucet key's things by names rather than by the id number (eg port number, vid or dp_id). We can do this easily without breaking existing configs. My plan is that we check if a dp_id is configured elsewhere. If not then the key is the dp_id. So this will not break existing configs so doesnt need a new config version.

So the config for valve would look more like:
```
---
   version: 2
 
   dps:
      test-switch-1:
           dp_id: 0x000000000002
           interfaces:
               1:
                   native_vlan: 2040
                   acl_in: 1
       test-switch-2:
           dp_id: 0x000000000002
           interfaces:
               port_1:
                   of_number: 1
                   native_vlan: 2040
                   acl_in: 1
 
   vlans:
       "dev VLAN":
           vid: 2040
 
   acls:
       1:
           - rule:
               nw_dst: "172.0.0.0/8"
               dl_type: 0x800
               allow: 1
 
           - rule:
               dl_type: 0x0806
               allow: 1
 
           - rule:
               nw_dst: "10.0.0.0/16"
               dl_type: 0x800
               allow: 0
```

And just a reminder, this will work so that the name used for the key will be the default value for the numeric id of the object (if it has one) and as the name of the object. Either of these can be rewritten, but I think we should try to deprecate that usage.

I add a file called parser.py this handles parsing configs for faucet and gauge. It reads in yaml files, builds configs and calls the factories and return fully built valve/gauge objects.

I added a file which I am currently calling poller.py (I would like a better name for this since it refers to both pollers and event loggers---actually come to think of it maybe logger is a better generic name). This has all the code for the loggers and pollers and the main gauge class sits in its own thread.

So I guess the most important question I have is about how we would like routers to be configured going forward. I feel like these should not be tied to vlans, since you might want to route between vlans, but perhaps the ryu bgp design means that makes sense?

And does anyone have any issues with this?
