### ISSUE TITLE
How to setup Gauge?

### ISSUE THREAD

**Issue by priyesh9875** [REANNZ/faucet#414]
I am trying to run gauge

I can see switch `s1` is added in both faucet and gauge controller, but  I am not getting any stats from switch
my gauge log
```
Feb 26 01:57:20 gauge  INFO     DPID 1 (0x1) up
Feb 26 01:57:35 gauge  INFO     port stats request timed out for s1
Feb 26 01:57:40 gauge  INFO     port stats request timed out for s1
```

My VM IP: 192.168.16.129, 192.168.171.131
my config files:
- faucet.yaml
```
version: 2
vlans:
    4090:
        name: "trusted network"
        unicast_flood: True
dps:
    s1:
        dp_id: 1
        description: "Switch"
        interfaces:
            1:
                native_vlan: 4090
                name: "port1.0.1"
            2:
                native_vlan: 4090
                name: "port1.0.2"
```

- gauge.yaml
```
version: 2
faucet_configs:
    - '/etc/ryu/faucet/faucet.yaml'
watchers:
    port_state_poller:
        type: 'port_state'
        dps: ['s1']
        db: 'influx'
        interval: 5

    port_stats_poller:
        type: 'port_stats'
        dps: ['s1']
        db: 'influx'
        interval: 5
dbs:
    influx:
        type: 'influx'
        influx_db: 'faucet'
        influx_host: 'localhost'
        influx_port: 8086
        influx_user: 'faucet'
        influx_pwd: '123'
        influx_timeout: 10
```

Steps I followed:
- Start controller
  `sudo ryu-manager  --ofp-tcp-listen-port=6633 faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py`
- Start mininet and add gauge controller
  `sudo mn  --mac --controller=remote,ip=192.168.16.129`
   `sh ovs-vsctl set-controller s1 tcp:192.168.16.129:6633 tcp:192.168.16.129:6663`
- Start gauge controller
  `sudo ryu-manager --verbose --ofp-tcp-listen-port=6663 faucet/src/ryu_faucet/org/onfsdn/faucet/gauge.py
`

Always getting `port stats request timed out for s1`

**Comment by anarkiwi** [comment]
Looks like there is some kind of connectivity problem (gauge is not receiving replies). It would be good to troubleshoot gauge<->OVS connectivity. 
If you find a bug within gauge that's causing the problem, please do reopen this issue with the details. You can also look at the existing unit tests that run Gauge for an example of running Gauge successfully within Mininet.

**Comment by priyesh9875** [comment]
I tried ovs-vsctl, it shows me both controllers are connected
```
mininet>sh ovs-vsctl show
f1d910ec-c953-40bf-acdc-15d3ade32575
    Bridge "s1"
        Controller "tcp:192.168.16.129:6633"
            is_connected: true
        Controller "tcp:192.168.16.129:6663"
            is_connected: true
```
----

Can you specify how to troubleshoot gauge<->OVS connectivity?
I am not able to understand unit test, can you  please give me bare minimal faucet-gauge mininet example.

**Comment by priyesh9875** [comment]
If I change watchers db from `influx` type to `text` type, I am getting correct data written in file.
```
version: 2
faucet_configs:
    - '/etc/ryu/faucet/faucet.yaml'

watchers:
    port_stats_poller:
        type: 'port_stats'
        dps: ['s1']
        db: 'ft_file' # influx throws port stats request timed out 
        interval: 5
dbs:
    influx:
        type: 'influx'
        influx_db: 'faucet2'
        influx_host: 'localhost'
        influx_port: 8086

    ft_file:
        type: 'text'
        file: 'ports.out.json' # Getting correct data written in file



```
