### ISSUE TITLE
Faucet documentation is not current

### ISSUE THREAD

**Issue by wackerly** [REANNZ/faucet#472]
The documentation in src/docs/INSTALL is out-of-date, because it references "upstart" when that no longer works and is no longer necessary. See the following thread for a recommendation from Shivaram for the proper install process:

https://lists.geant.org/sympa/arc/faucet-users/2017-03/msg00009.html

The src/docs/INSTALL documentation should be updated to match the current expected install process. At the same time, the documentation in README.rst should also be updated, as it describes another method of running (using ryu-manager) that requires setting environment variables.

**Comment by gizmoguy** [comment]
Adding to this, FAQ.rst and README.rst along with other documentation is way out of date.

**Comment by byllyfish** [comment]
I believe the syntax for acl rules in README.rst needs to be fixed:

```yaml
        - rule:
            nw_dst: "172.0.0.0/8"
            dl_type: 0x800
            allow: 1
```

should be:

```yaml
        - rule:
            nw_dst: "10.0.0.0/8"
            dl_type: 0x800
            actions:
                allow: 1
```
