### ISSUE TITLE
Field masks used unnecessarily on exact match - IPv4, IPv6

### ISSUE THREAD

**Issue by byllyfish** [REANNZ/faucet#493]
I've noticed a few places where Faucet uses field masks for an exact match on an IPv4 or IPv6 address.  It doesn't seem to hurt anything, but I think it's unnecessary.

```yaml
---
type:            FLOW_MOD
time:            1491349340.242006000
xid:             0xFFA1AC8F
version:         0x04
conn_id:         6
src:             127.0.0.1:6653
dst:             127.0.0.1:33754
msg:             
  cookie:          0x000000005ADC15C0
  cookie_mask:     0x0000000000000000
  table_id:        0x03
  command:         ADD
  idle_timeout:    0x0000
  hard_timeout:    0x0000
  priority:        0x23AB
  buffer_id:       NO_BUFFER
  out_port:        0x00000000
  out_group:       0x00000000
  flags:           [  ]
  match:           
    - field:           ETH_TYPE
      value:           0x0806
    - field:           VLAN_VID
      value:           0x17F8
    - field:           ARP_TPA
      value:           10.10.10.1
      mask:            255.255.255.255     # Don't need mask on exact match
  instructions:    
    - instruction:     APPLY_ACTIONS
      actions:         
        - action:          OUTPUT
          port_no:         CONTROLLER
          max_len:         0x0080
    - instruction:     GOTO_TABLE
      table_id:        0x06
---
type:            FLOW_MOD
time:            1491349340.242018000
xid:             0xFFA1AC91
version:         0x04
conn_id:         6
src:             127.0.0.1:6653
dst:             127.0.0.1:33754
msg:             
  cookie:          0x000000005ADC15C0
  cookie_mask:     0x0000000000000000
  table_id:        0x04
  command:         ADD
  idle_timeout:    0x0000
  hard_timeout:    0x0000
  priority:        0x23AB
  buffer_id:       NO_BUFFER
  out_port:        0x00000000
  out_group:       0x00000000
  flags:           [  ]
  match:           
    - field:           ETH_TYPE
      value:           0x0800
    - field:           VLAN_VID
      value:           0x17F8
    - field:           IP_PROTO
      value:           0x01
    - field:           IPV4_SRC
      value:           10.0.0.0
      mask:            255.0.0.0
    - field:           IPV4_DST
      value:           10.10.10.1
      mask:            255.255.255.255    # Don't need mask for exact match
  instructions:    
    - instruction:     APPLY_ACTIONS
      actions:         
        - action:          OUTPUT
          port_no:         CONTROLLER
          max_len:         0x0080
---
type:            FLOW_MOD
time:            1491349341.206877000
xid:             0xFFA1ACD6
version:         0x04
conn_id:         6
src:             127.0.0.1:6653
dst:             127.0.0.1:33754
msg:             
  cookie:          0x000000005ADC15C0
  cookie_mask:     0x0000000000000000
  table_id:        0x04
  command:         ADD
  idle_timeout:    0x0000
  hard_timeout:    0x0000
  priority:        0x23AB
  buffer_id:       NO_BUFFER
  out_port:        0x00000000
  out_group:       0x00000000
  flags:           [  ]
  match:           
    - field:           ETH_TYPE
      value:           0x0800
    - field:           VLAN_VID
      value:           0x17F8
    - field:           IPV4_DST
      value:           10.0.0.1
      mask:            255.255.255.255    # Don't need mask for exact match
  instructions:    
    - instruction:     APPLY_ACTIONS
      actions:         
        - action:          SET_FIELD
          field:           ETH_SRC
          value:           '0e:00:00:00:00:01'
        - action:          SET_FIELD
          field:           ETH_DST
          value:           'ce:1d:40:de:0d:8e'
        - action:          DEC_NW_TTL
    - instruction:     GOTO_TABLE
      table_id:        0x06
---
type:            FLOW_MOD
time:            1491349340.250914000
xid:             0xFFA1ACBA
version:         0x04
conn_id:         6
src:             127.0.0.1:6653
dst:             127.0.0.1:33754
msg:             
  cookie:          0x000000005ADC15C0
  cookie_mask:     0x0000000000000000
  table_id:        0x05
  command:         ADD
  idle_timeout:    0x0000
  hard_timeout:    0x0000
  priority:        0x240B
  buffer_id:       NO_BUFFER
  out_port:        0x00000000
  out_group:       0x00000000
  flags:           [  ]
  match:           
    - field:           ETH_TYPE
      value:           0x86DD
    - field:           VLAN_VID
      value:           0x17F8
    - field:           IP_PROTO
      value:           0x3A
    - field:           IPV6_DST
      value:           'fc00::10:10:10:1'
      mask:            'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff'     # Don't need mask for exact match
    - field:           ICMPV6_TYPE
      value:           0x80
  instructions:    
    - instruction:     APPLY_ACTIONS
      actions:         
        - action:          OUTPUT
          port_no:         CONTROLLER
          max_len:         0x0080
```

The YAML output above is produced using my oftr tool:
https://launchpad.net/~byllyfish/+archive/ubuntu/oftr

I'm using latest master (2017-04-04). I have two faucet_vips: [ "10.10.10.1/8", "fc00::10:10:10:1/64" ]
